version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: zhenyasonic/kittygram_backend
    env_file: .env
    volumes:
      - static_volume_kit:/backend_static/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: zhenyasonic/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_kit:/frontend_static/
    depends_on:
      - backend
    
  gateway:
    image: zhenyasonic/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume_kit:/staticfiles/
    ports:
      - 9000:80
    depends_on:
      - frontend
      - backend